package jpp;
// Generated by makedfa
public interface IJPPTokens {
static final int
 J_WHITESPACE = 256,
 J_CMDSTART = 257,
 J_ENUM = 258,
 J_ENUM2 = 259,
 J_PUBLIC = 260,
 J_PRIVATE = 261,
 J_PROTECTED = 262,
 J_PACKAGE = 263,
 J_PREFIX = 264,
 J_WITHLENGTHS = 265,
 J_STRS = 266,
 J_NAME = 267,
 J_CHARS = 268,
 J_VERBATIM = 269,
 J_INTCONST = 270,
 J_ID = 271,
 J_STRING = 272;
}
